<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , webpack-dev-server-cli_baf6c8</name>
   <tag></tag>
   <elementGuidId>810266a1-799b-41a4-add4-931fd77491dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#webpack-dev-server-client-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='webpack-dev-server-client-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#webpack-dev-server-client-overlay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>40642ecb-64e3-48a5-868a-8b91968ad2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>webpack-dev-server-client-overlay</value>
      <webElementGuid>ebeb06bc-6803-4814-ada6-26d27cd15127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>7467bccb-41b2-4a62-930e-2932de44c3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webpack-dev-server-client-overlay&quot;)</value>
      <webElementGuid>6b0f8cd0-a5cf-4ba4-b286-8fe0291c0189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='webpack-dev-server-client-overlay']</value>
      <webElementGuid>6df94001-e9f2-4591-b79b-bfe507186961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>18880f8f-3472-4028-a15f-263d797b46b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'webpack-dev-server-client-overlay' and @src = 'about:blank']</value>
      <webElementGuid>9a4df8e8-9d8c-469e-bc67-20c560a9763d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
